### ISSUE TITLE
Fix bug with redirecting and saving pets on Comparison page

### ISSUE THREAD

**Issue by ivan-bonk** [IvanBonk/FE-LAB-12-Team-Snow-Project#180]
Added the dogs, returned to the Result page, removed the dog, and returned to the Comparison page
Pets to compare does not update

**Comment by ivan-bonk** [comment]
I don't think that's the bug
If the user clicks on the browser's "back" button - it takes him to the page where he was before, that is, with the same set of animals

**Comment by Pashkaua** [comment]
So if this is not a mistake, we can close this issue.
